apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Kubernetes</title>
      <style>
        body {
          background-color: #303030;
          color: white;
          font-family: Arial, sans-serif;
          text-align: center;
          margin: 0;
          padding: 20px;
        }
        .kubernetes-logo {
          width: 50px;
          height: 50px;
          margin-bottom: 10px;
        }
      </style>
    </head>
    <body>
      <img class="kubernetes-logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+PHBhdGggZmlsbD0iIzMyNmNlNSIgZD0iTTE1Ljk4NCAyYTEuNDcxIDEuNDcxIDAgMCAwLS41NzguMTI1bC05LjM3NSAzLjYyNWExLjQ2IDEuNDYgMCAwIDAtLjkwNiAxLjM3NnY5Ljc1YzAgLjIzNi4wNTkuNDU3LjE2OC42NThsMTUuOTQ1IDYuODgxYTEuNTMgMS41MyAwIDAgMCAxLjE5MS4wMWwxMC43OTctNC4xNTZjLjQ0Ni0uMT72L5"></img>
      <h1>Hello from app1.</h1>
      <p>pod: <span id="pod-name"></span></p>
      <p>node: <span id="node-name"></span></p>
      <script>
        document.getElementById('pod-name').innerText = process.env.POD_NAME;
        document.getElementById('node-name').innerText = process.env.NODE_NAME;
      </script>
    </body>
    </html>
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: nginx
        ports:
        - containerPort: 80
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: app-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: app-content
        configMap:
          name: app1-config
---

apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    app: app1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
