apiVersion: v1
kind: ConfigMap
metadata:
  name: app2-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Kubernetes</title>
      <style>
        body {
          background-color: #303030;
          color: white;
          font-family: Arial, sans-serif;
          text-align: center;
          margin: 0;
          padding: 20px;
        }
        .kubernetes-logo {
          width: 50px;
          height: 50px;
          margin-bottom: 10px;
        }
      </style>
    </head>
    <body>
      # <img class="kubernetes-logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+PHBhdGggZmlsbD0iIzMyNmNlNSIgZD0iTTE1Ljk4NCAyYTEuNDcxIDEuNDcxIDAgMCAwLS41NzguMTI1bC05LjM3NSAzLjYyNWExLjQ2IDEuNDYgMCAwIDAtLjkwNiAxLjM3NnY5Ljc1YzAgLjIzNi4wNTkuNDU3LjE2OC42NThsMTUuOTQ1IDYuODgxYTEuNTMgMS41MyAwIDAgMCAxLjE5MS4wMWwxMC43OTctNC4xNTZjLjQ0Ni0uMTcyLjc3NS0uNTc4Ljg0OC0xLjA1OVYxMC4xNWMwLS4yMy0uMDU3LS40NS0uMTYtLjY0N2wtOS4xODYtNi45MDVhMS40ODYgMS40ODYgMCAwIDAtLjkxOC0uNTk4eiIvPjxwYXRoIGZpbGw9IiNmZmYiIGQ9Ik0xNiA4LjJhNy44IDcuOCAwIDEgMCAwIDE1LjYgNy44IDcuOCAwIDAgMCAwLTE1LjZ6bTAgMTMuNWE1LjcgNS43IDAgMSAxIDAtMTEuNCA1LjcgNS43IDAgMCAxIDAgMTEuNHoiLz48L3N2Zz4=" alt="Kubernetes Logo">
      <h1>Hello from app2.</h1>
      <p>pod: <span id="pod-name">app-one-5c75c6d3-9n64n</span></p>
      <p>node: <span id="node-name">Linux (4.19.0-24).1.x86_64</span></p>
    </body>
    </html>
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: httpd
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: app-content
        configMap:
          name: app2-config
---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
