apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  index.template.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Kubernetes - HTTPD</title>
      <style>
        body {
          background-color: #303030;
          color: white;
          font-family: Arial, sans-serif;
          text-align: center;
          margin: 0;
          padding: 20px;
        }
        .kubernetes-logo {
          width: 50px;
          height: 50px;
          margin-bottom: 10px;
        }
      </style>
    </head>
    <body>
      <img class="kubernetes-logo" src="https://upload.wikimedia.org/wikipedia/commons/3/39/Kubernetes_logo_without_workmark.svg" alt="Kubernetes Logo">
      <h1>Hello from app2 (HTTPD)</h1>
      <p>Pod Name: <span id="pod-name">${POD_NAME}</span></p>
      <p>Node Name: <span id="node-name">${NODE_NAME}</span></p>
    </body>
    </html>

  start.sh: |
    #!/bin/sh
    echo "Starting HTTPD configuration..."
    echo "POD_NAME is: $POD_NAME"
    echo "NODE_NAME is: $NODE_NAME"
    
    cp /usr/local/apache2/htdocs/index.template.html /tmp/index.html
    sed -i "s/\${POD_NAME}/$POD_NAME/g" /tmp/index.html
    sed -i "s/\${NODE_NAME}/$NODE_NAME/g" /tmp/index.html
    cp /tmp/index.html /usr/local/apache2/htdocs/index.html

    echo "Files in /usr/local/apache2/htdocs/"
    ls -l /usr/local/apache2/htdocs/

    # Vérifier si HTTPD tourne déjà
    if pgrep httpd > /dev/null; then
      echo "HTTPD is already running"
    else
      echo "Starting HTTPD..."
      exec httpd-foreground
    fi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namesapce: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: httpd
        ports:
        - containerPort: 80
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command: ["/bin/sh", "-c", "cp /start.sh /tmp/start.sh && chmod +x /tmp/start.sh && /tmp/start.sh"]
        volumeMounts:
        - name: config-volume
          mountPath: /usr/local/apache2/htdocs/index.template.html
          subPath: index.template.html
        - name: script-volume
          mountPath: /start.sh
          subPath: start.sh
      volumes:
      - name: config-volume
        configMap:
          name: app-config
      - name: script-volume
        configMap:
          name: app-config

---
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
